ALLUSERSPROFILE=C:\ProgramData
APPDATA=C:\Users\maral\AppData\Roaming
CommonProgramFiles=C:\Program Files\Common Files
CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files
CommonProgramW6432=C:\Program Files\Common Files
COMPUTERNAME=MAR
ComSpec=C:\WINDOWS\system32\cmd.exe
DriverData=C:\Windows\System32\Drivers\DriverData
EFC_7932_1592913036=1
HOMEDRIVE=C:
HOMEPATH=\Users\maral
LOCALAPPDATA=C:\Users\maral\AppData\Local
LOGONSERVER=\\MAR
NUMBER_OF_PROCESSORS=8
OneDrive=C:\Users\maral\OneDrive
OneDriveConsumer=C:\Users\maral\OneDrive
OS=Windows_NT
Path=C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Git\cmd;C:\Users\maral\AppData\Local\Microsoft\WindowsApps;C:\Users\maral\AppData\Local\Programs\Microsoft VS Code\bin
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
PROCESSOR_ARCHITECTURE=AMD64
PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 142 Stepping 12, GenuineIntel
PROCESSOR_LEVEL=6
PROCESSOR_REVISION=8e0c
ProgramData=C:\ProgramData
ProgramFiles=C:\Program Files
ProgramFiles(x86)=C:\Program Files (x86)
ProgramW6432=C:\Program Files
PROMPT=$P$G
PSModulePath=C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules
PUBLIC=C:\Users\Public
SESSIONNAME=Console
SystemDrive=C:
SystemRoot=C:\WINDOWS
TEMP=C:\Users\maral\AppData\Local\Temp
TMP=C:\Users\maral\AppData\Local\Temp
USERDOMAIN=MAR
USERDOMAIN_ROAMINGPROFILE=MAR
USERNAME=maral
USERPROFILE=C:\Users\maral
windir=C:\WINDOWS
ZES_ENABLE_SYSMAN=1
